### ISSUE TITLE
ADD Cluster and TransactionalID ACLs to AKHQ Dashboard ACLs Info

### ISSUE THREAD

**Issue by javier-torres** [tchiotludo/akhq#1084]
Hello,

We are delighted with the work done by AKHQ, we have been using it for some time in our organization and it is wonderful.

The main reason why we decided to use AKHQ and not another Kafka Web UI was because you can see the ACLs. 

Today, we are working with MSK and Confluent tools like ksqlDB Server, Schema Registry and Kafka Connect and we are extending our ACLs a lot, we came across limitations of AKHQ which do not allow us to see the ACLs at Cluster level and TransactionalID, only show ACLs for Topics and Groups

Would it be possible to add these features to the AKHQ interface?

If it were possible it would be a great advance for AKHQ and it would be great for our organization.

Thank you very much.

![image](https://user-images.githubusercontent.com/59615952/165463791-9c7649d0-b7b2-4264-a266-ce16f6b6eca3.png)

**Comment by tchiotludo** [comment]
don't seems complicated, als o like this one : https://github.com/tchiotludo/akhq/issues/266

PR are welcome :+1:

**Comment by 10xtechie** [comment]
@tchiotludo 
I totally agree with you that these features don't seem to be complicated to be implemented - especially ACLs at Cluster level. There is no api code for ACLs at TransactionalID level though. 
I have started looking into it, however, I am getting `'No ACLS found, or the "authorizer.class.name" parameter is not configured on the cluster.'` . I have set up my development environment using `docker-compose -f docker-compose-dev.yml up and authorizer.class.name: kafka.security.authorizer.AclAuthorizer` in application-dev.yml file. 
Could you please tell me how to resolve this issue so that I can access http://localhost:3000/ui/local/acls without that message? 
Also, you can assign this issue #1084 to me :)

**Comment by tchiotludo** [comment]
@10xtechie: 
You only need to add some acls to the cluster first: 
```
docker-compose exec kafka  bash
kafka-acls --bootstrap-server localhost:9092  --add --allow-principal User:* --operation All --topic testTopic
```
After you will see some acls on the ui.
The ticket is for you ;)

**Comment by javier-torres** [comment]
Hello,

I just updated AKHQ to the latest version 0.21.0 to display the ACLs at Cluster and TransactionalID level but I can't see it in my UI

![imagen](https://user-images.githubusercontent.com/59615952/171344613-6a8d3bc8-9264-47a4-abc6-f141633909dd.png)
