### ISSUE TITLE
Logo missing on Login Screen in dev docker Container

### ISSUE THREAD

**Issue by jheinitz** [tchiotludo/akhq#1443]
Hello,

we are using `0.23.0` of AKHQ which is working fine. we have configured basic-auth for the UI with noaccess to be the default. This means that the Login screen appears when we open the URL in the Browser. 
Today I made some tests using the latest `dev` image and I recognized that the **AKHQ Logo is missing on the Login Screen**. Is there a reason for this and will it be available in the next official release? 

Please let me know if you need anything else from my side to find the reason for the missing logo.

Kind regards
Jens

**Comment by tchiotludo** [comment]
it's clearly a bug, we need to fix that before the imminent release :cry:

**Comment by jheinitz** [comment]
I don't know if it is related, but I use these `html-head:` settings to display a colored string under the logo:
```
  html-head: "<style type=\"text/css\">\n  .logo-wrapper:after {\n    display: block;\n
    \   content: \"test\";\n    height: 24px;\n    position: relative;\n    text-transform:
    capitalize;\n    font-weight: bold;\n    text-align: center;\n    background-color:
    darkgreen;\n    color: white;\n    font-size: 24px;\n    margin-top: 8px;\n  }\n</style>\n"
```
This works fine with `0.23.0` but does not work with the latest `dev` docker image.

Any idea?

**Comment by AlexisSouquiere** [comment]
The issue seems to be linked to a wrong URI when loading the logo.

0.23.0
![image](https://user-images.githubusercontent.com/2262145/229049119-ebe95d77-e5eb-4748-bd42-f3ed52de82a8.png)

dev image (/ui/ui/static/...)
![image](https://user-images.githubusercontent.com/2262145/229049584-54b08849-8903-4dd8-8106-ed1873faf2fc.png)

I don't know yet what is the issue and what could have changed on assets management. I'll try to take some time to investigate

**Comment by tooptoop4** [comment]
maybe https://github.com/tchiotludo/akhq/pull/1355 is related or https://github.com/micronaut-projects/micronaut-core/issues/8948?

**Comment by AlexisSouquiere** [comment]
For me there is no link with this PR or even Micronaut. #1355 is related to the returnTo variable that is set when leaving a component. The issue with Micronaut is about context-path that we don't use by default (we use it in my organization that why a fixed issue on it). I would think about something related to webpack.

I'm seeing a new entry in the asset-manifest.json for the logo
![image](https://user-images.githubusercontent.com/2262145/229334058-3fdaba69-eca0-427c-9cf5-1f4a82aab965.png)

We don't have it in 0.23.0 or with another key 
![image](https://user-images.githubusercontent.com/2262145/229334095-4369812f-becc-4726-80ad-e5e138631be1.png)

This new entry could explain that we try to retrieve the logo from /ui/ui because of the relative ./ui path. 

@lucapette any idea ?

**Comment by tooptoop4** [comment]
how about this theory? https://github.com/tchiotludo/akhq/commit/dd8ea4f249261605facbd18160328b8195e348b2 upgraded "react-scripts" from "3.4.1" to "^5.0.1", https://github.com/facebook/create-react-app/blob/v3.4.1/packages/react-scripts/package.json#L79 shows "webpack": "4.42.0" while https://github.com/facebook/create-react-app/blob/v5.0.1/packages/react-scripts/package.json#L74 shows "webpack": "^5.64.4".  https://stackoverflow.com/questions/71254243/webpack-5-webpack-tries-to-resolve-root-relative-paths-to-images-in-scss-or-c has reference to https://github.com/webpack/webpack/issues/15499 which sounds a little similar and mentions that it worked in webpack 4 but not webpack 5

**Comment by jheinitz** [comment]
Hi! Thanks for fixing it. I will give it a try as soon as the new docker image is available and give feedback here.

**Comment by tchiotludo** [comment]
done in #1449
