### ISSUE TITLE
Couldn't delete topic's message after upgrading to 0.24.0

### ISSUE THREAD

**Issue by VisionaryAries** [tchiotludo/akhq#1458]
Couldn't delete message in AKHQ UI after upgrading to 0.24.0, It doesn't work when clicking the OK button. And we checked the permission are correct.
![image](https://user-images.githubusercontent.com/55009215/230816642-bf20d76e-2670-4802-a652-0dd245638772.png)

**Comment by AlexisSouquiere** [comment]
@VisionaryAries I experienced the same issue locally. I don't know why we have this issue because nothing changed in the source code but adding the buffer library + changing `new Buffer` by `Buffer.from` in [TopicData.jsx](https://github.com/tchiotludo/akhq/blob/dev/client/src/containers/Topic/Topic/TopicData/TopicData.jsx#L460) seems to fix the issue

If you have time you can test it and submit the PR. Otherwise I'll do it when I have time
