### ISSUE TITLE
Searching messages is currently ridiculously slow

### ISSUE THREAD

**Issue by jonasvoelcker** [tchiotludo/akhq#1834]
When searching in a topic containing much data, the search will never finish due to a combination of a poll-timeout of 1 second combined with max.poll.records of 50.

**Comment by jonasvoelcker** [comment]
If the max.poll.records are increased there is also a problem with the oldest listing as it returns a list, which is way too large:

![image](https://github.com/tchiotludo/akhq/assets/47037735/775c9d68-3dd8-44ce-87c3-16ef8c20ad78)

![image](https://github.com/tchiotludo/akhq/assets/47037735/171d0a99-f2f0-4310-996d-32ef30a12d2a)

https://github.com/tchiotludo/akhq/pull/1840

**Comment by AlexisSouquiere** [comment]
I tried your 2 fixes (config update + limit on oldest consume) but for me there is still the default 50 records limit applied consumer max.poll.records because of this line:

https://github.com/tchiotludo/akhq/blob/ff3acaffbc9b475a7d7d3a259c3fbda341c193f5/src/main/java/org/akhq/repositories/RecordRepository.java#L656

size will always be 50 if you keep the default value. But increasing it will increase the number of records that will be displayed

https://github.com/tchiotludo/akhq/blob/ff3acaffbc9b475a7d7d3a259c3fbda341c193f5/src/main/java/org/akhq/repositories/RecordRepository.java#L1269

Don't you have the same behaviour ?

**Comment by AlexisSouquiere** [comment]
I tried to remove the property from the consumer in the search function but the 50 records limit to be displayed in the UI is not applied anymore I was showing hundreds of matching records. We probably have to apply it later, probably here
https://github.com/tchiotludo/akhq/blob/b566b8c384794b789f7615aef6cac5a159d99c17/src/main/java/org/akhq/repositories/RecordRepository.java#L728-L731

**Comment by jonasvoelcker** [comment]
Hi @AlexisSouquiere,

thanks a lot for the detailed checks :)

I've worked on that and came to this solution: https://github.com/tchiotludo/akhq/pull/1843

Feel free to doublecheck it as well ;)

Best Regards
Jonas
