### ISSUE TITLE
How to disable topic data visibility on AKHQ UI

### ISSUE THREAD

**Issue by nikesh1906** [tchiotludo/akhq#1904]
Hi Team,
I don’t to view topic data on AKHQ UI due to some compliance, is there a way to disable topic data visibility in UI.

**Comment by nikesh1906** [comment]
Hi @tchiotludo can you please help on this, we don’t want to see any topic data on the UI is there a way to disable it or is there a way to mask all the data for all the topics. I tried data masking but it’s not working.

**Comment by nikesh1906** [comment]
Hi @tchiotludo @AlexisSouquiere @lucapette 
Can anyone of you please help with this request. We don’t want to see any data on the UI and mask all the visible data. Can you please provide a way to implement this.

**Comment by alozano3** [comment]
Hi, you can achieve that by not granting the READ action to the TOPIC_DATA resource in your application.yml. You can check the documentation for more information https://akhq.io/docs/configuration/authentifications/groups.html.

**Comment by nikesh1906** [comment]
Hi @alozano3 If i remove READ action from TOPIC_DATA I am not able to view any of the topics and topic tab is completely vanished from UI.
Only Nodes, Consumer Group and Settings tabs are visible.

**Comment by nikesh1906** [comment]
Hi @alozano3  I removed [TOPIC_DATA] from topic admin role after restarting the entire akhq-ui is blank no data is visible. If i remove READ action I can’t see any topics in akhq-ui only nodes, consumer groups are visible.

**Comment by AlexisSouquiere** [comment]
I'm able to achieve what you need with the following setup:
- Resource TOPIC and action READ granted to the user
- Either resource CONSUMER_GROUP and action READ granted to the user (because the topics list screen tries to load consumer groups for the topics) or skip consumer groups loading with `akhq.ui-options.topic.skip-consumer-groups` set to false (https://akhq.io/docs/configuration/akhq.html#topics).

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/9cb88989-fb14-4df2-860f-a033883f8e73">

Please reopen if it doesn't work and give your configuration to investigate
