### ISSUE TITLE
Feature request: ability to turn off rest-api

### ISSUE THREAD

**Issue by RickardCardell** [tchiotludo/akhq#278]
The new and shiny rest-api is a nice feature.
However, given that the current status of the rest-api is experimental, I think that an ability to turn it on and off by a configuration is appropriate.

**Comment by tchiotludo** [comment]
Hi @RickardCardell ,
The API is experimental for now but really soon, this one will be mandatory ! 😀
I call it experimental because the signature off some method will evolve quickly.
I have no real doubt on the security and so on.

For all this reason, I don't think an feature flag will be appropriate 😀

**Comment by tchiotludo** [comment]
closing since no response
