### ISSUE TITLE
Supproting list of urls schema registry

### ISSUE THREAD

**Issue by lciolecki** [tchiotludo/akhq#343]
Right now akhq supports only single url to schema registry.. In real big data env we have a few instances of schema registry. It would  be nice when akhq also supports list of urls to schema registry.

WDYT?

**Comment by tchiotludo** [comment]
Interesting, and to be honest a little bit surprised !
You have multiple schema registry for the same Kafka cluster ?
Seems to be a bit complicated setup, since consumer need to have a map of topics / registry url ?
Never heard about this kind of setup !

From akhq side, seems to be a little bit tricky, need to try / catch every registry instance to try to deserialize message.

**Comment by lciolecki** [comment]
Yep, we have set schema registry in cluster as kafka allows for it: https://docs.confluent.io/current/schema-registry/connect.html#configuration-options look at `schema.registry.url`  it's comma-separated list of URLs.

We have few instances of schema registry connected to to list of `kafkastore.bootstrap.servers`.  All schemas informations are keeped in zookeeper which is clustered :)

It's important when you want to support high availability for it.

**Comment by tchiotludo** [comment]
Ok it's only for HA ! better understand ! 
Will be easy to support it so :+1:

**Comment by tchiotludo** [comment]
You can try with dev version ;)
