### ISSUE TITLE
Error when accessing Schema Registry

### ISSUE THREAD

**Issue by AntAreS24** [tchiotludo/akhq#354]
Hi,

I'm trying to configure the Schema Registry (TIBCO Implementation, not Confluent) and I'm getting the following error on the screen: `No matching content type. Best choice is 'application/vnd.schemaregistry.v1+json; charset=UTF-8'; error code: 406`.

Is there a way to configure that in the `application.yaml`?

**Comment by tchiotludo** [comment]
I have a look, it will need an update on akhq side, since the headers are not changed globally, we need to change it for every query we do to the schema registry ... 
But seems weird that TIBCO refuse the official one from confluent, it mean that no Java app is able to talk with this registry (without tuning) and some java app will never work (KafkaStream I think for example).

Maybe it will be better to report the issue to TIBCO IMO !

**Comment by AntAreS24** [comment]
@tchiotludo thanks for looking into that.

I've opened-up the Swagger for the Schema Registry and this is the sample request executed:
`curl -X GET "https://host:8081/schema/v1/config" -H "accept: application/json"`

And the response headers:
```
content-length: 33 
content-type: application/vnd.schemaregistry.v1+json; charset=UTF-8 
date: Mon, 17 Aug 2020 22:56:03 GMT 
status: 200
```

Happy to raise an SR with TIBCO, but I need to understand what AKHQ is expecting vs. what its sending/receiving. Is there a way to debug that out?

Ben

**Comment by tchiotludo** [comment]
As I seen in the source code, Java official client for SR expect an exact `content-type: application/vnd.schemaregistry.v1+json` without `;charset=UTF-8 ` and raise an error with that. 
Mostly it's [here]( 
https://github.com/confluentinc/schema-registry/blob/2982588308ad64448eea2257e6490164dac2b20b/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L155) & [here](https://github.com/confluentinc/schema-registry/blob/8f727d74da65a9be4f7fd82fd8a2498ad48c85ec/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/Versions.java#L24)

So, we need to change it on client side since TIBCO expect exactly  `application/vnd.schemaregistry.v1+json; charset=UTF-8`
I think if you send `curl -X GET "https://host:8081/subjects" -H "content-type: application/vnd.schemaregistry.v1+json"`
you will have the same error, right ?

**Comment by AntAreS24** [comment]
Sorry for the late reply.

Indeed, I'm getting a similar error:
`{"error_code":406,"message":"No matching content type.  Best choice is 'application/vnd.schemaregistry.v1+json; charset=UTF-8'"}`

I'll raise the error with TIBCO and come back here to report.

**Comment by AntAreS24** [comment]
After looking into that a bit further, I don't think it will work anyway since the SERDE for TIBCO is different than Confluent... Which means even if I can pass through this Content-Type issue, it will fail SERDE.

**Comment by tchiotludo** [comment]
I think so looking at [here](https://docs.tibco.com/pub/msg-akd-bridge/2.1.0/doc/html/GUID-9DD42DED-F0F7-4321-AA25-80E8BEEFA4E5.html) & [here](https://docs.tibco.com/pub/msg-akd-bridge/2.1.0/doc/html/GUID-15D61DC0-AC3F-4F91-8E7A-86495D568048.html)
As I see there is a special proprietary jar to include on application that produce the message. 
I can't see the source code to understand the format but seems to be a special format.

I'll close this since we can't include the proprietary jar due to licensing issue.

**Comment by AntAreS24** [comment]
Is there a way we could fork the repo and change the SERDE? Do you have any pointers for us?

**Comment by tchiotludo** [comment]
not really easy this one ... 

The whole logic of deserialize is here : https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Record.java#L109

Just replace the one with the TIBCO one .. et voila ... :smile:

**Comment by AntAreS24** [comment]
For those accessing this issue, TIBCO has submitted a PR for that: https://github.com/tchiotludo/akhq/pull/393

**Comment by tchiotludo** [comment]
That is already merged 🤘

**Comment by zejji** [comment]
@tchiotludo - I'm seeing this issue when trying to use AKHQ with the Apicurio schema registry (see issue [here](https://github.com/Apicurio/apicurio-registry/issues/1007)). Do you know exactly what headers AKHQ currently sends? Also, does it use content negotation? It would be nice if AKHQ could be made to work successfully with Apicurio schema registry as it is the main alternative schema registry implementation.

**Comment by tchiotludo** [comment]
@zejji seems that upstream handle the issue no ? no more issue from akhq I think ?
