### ISSUE TITLE
Quastion about api

### ISSUE THREAD

**Issue by chi-miel** [tchiotludo/akhq#418]
Hello,

i use the api to retrieve lag per partition, it's work perfectly !

I read that api is experimental, will it be remove in near futur ?

Otherwise , i will have to install other application like Burrow for this metric =/ ...

Thank you

**Comment by tchiotludo** [comment]
The api is experimental because the signature will be changed on near future.

For now, the api returned too many things (mostly on list) because on performance issue 

But you can be sure an endpoint will always be available on the api to have the lag (maybe you will need to do 2 query, one for the list and one per consumer group).

**Comment by chi-miel** [comment]
Ok, thank you !

**Comment by tchiotludo** [comment]
np :+1:
