### ISSUE TITLE
Displaying large messages in topics is stalling the UI

### ISSUE THREAD

**Issue by rlamcaiso** [tchiotludo/akhq#564]
Hello @tchiotludo.   Thank you for your tremendous effort with this project.  We are just starting to use the application in our Kafka development and it has been a big help.  

An issue that we are encountering is that the app would hang when we view a topic with many large messages.  Would it be possible to disable the message preview window, and provide a button for individual messages to view an abbreviated string of the message (ie. 250 characters) and with a download button to download the full message?

Thank you so much for your time.

Regards,
Rick

**Comment by tchiotludo** [comment]
What size is your "with many large messages"  ? 
250 is really to low so I need to understand where we need to put the limit (backend or frontend) !

**Comment by rlamcaiso** [comment]
Thank you for the prompt response.   Our bulk messages range from 2MB to 60MB, and there could be hundreds of these messages generated per day and published to the topic.

**Comment by tchiotludo** [comment]
ok so I your case, the need will be server side ! 
60 mb will always froze the brower :smile:

**Comment by rlamcaiso** [comment]
Yes.  We don't know how else to manage this performance issue with our current payloads.  I appreciate your help!

**Comment by EdwinFajardoBarrera** [comment]
Hello @tchiotludo, I would like to work on a solution to this, can u assign it to me?

**Comment by tchiotludo** [comment]
How will you handle this ?

**Comment by EdwinFajardoBarrera** [comment]
> How will you handle this ?

Well, I think the backend is required to catch large messages and only send a small preview. I see the limit is almost 10MB but if we send 10MB messages the problem could just persist, so maybe I think 5MB could be ok. What do you think?

**Comment by tchiotludo** [comment]
It's a good solution, please add a configuration options with a decent default value (5MB)

**Comment by EdwinFajardoBarrera** [comment]
Hello @tchiotludo, I still working on a solution to this issue. I'm catching the size of messages in the backend and the problem stills if there are many messages of length near to the limit (4.9MB for example) and I think cutting the message does not give a good UX because JSON format fails and maybe is not worth seeing only a cut part of a message. I'm thinking about only showing a message informing this situation and making more visible the "share" option to see the full message.

Something like this:

![image](https://user-images.githubusercontent.com/36389489/147698009-c8bc1563-a977-4960-aedd-9a6578538d4b.png)

What do you think?

**Comment by tchiotludo** [comment]
I still think the truncate is the better option than nothing, debugging without any message is impossible, I prefer a snippet 
Why not the share button can display the full message, it's a good idea.
