### ISSUE TITLE
Sorting messages in a topic clears search filters

### ISSUE THREAD

**Issue by mogggggg** [tchiotludo/akhq#609]
Hey there,
I'm using the latest version of AKHQ in Kubernetes with your Helm chart and have noticed that when I update the message sort order in a topic it will clear any search filters. I think this is a UI bug as there are no errors in the logs.

The particular topic I'm looking at is not especially big - it's only one partition and < 200k messages but I did have to increase the poll timeout from 1s to 10s to get the sort ordering to work when sorting by newest.

I've also tried updating the default ordering and filtering the results still resets that to `Oldest`.
Here's a gif:
![akhq](https://user-images.githubusercontent.com/40348003/108429537-3aabdc80-7294-11eb-9bb9-5666cb2c8e9e.gif)

Let me know if I can get you anymore info, thanks!

**Comment by tchiotludo** [comment]
Not really sure it's a bug, I can't remember for now if the search can be done with sort newest. 
Will look, thanks for the report

**Comment by r-roos** [comment]
Is there any update on this matter? I am currently in a situation where I would love to be able to just get the latest records when using a search.

**Comment by tchiotludo** [comment]
I've a quick look and the sort as from oldest. 
Seems to be complicated to inverse this because Kafka don't have any API to fetch in reverse order. 
The Newest sort is client side and not really performant (mean slow and resource intensive for the broker), for just a page I think it's ok since we know the count of request we do (1 max 2). 

For the search, this can lead millions of request depending if the search pattern can be found.
Not really sure I want to implement a search that will be slow for most of the case (and can be dangerous for the broker).

**Comment by r-roos** [comment]
Thanks for the quick response in this matter. With your explanation I understand why this feature is not implemented.

**Comment by abolfazlnasr** [comment]
it's necessary to sort our search results, or search in sorted data.
please take action for it. thanks

**Comment by tchiotludo** [comment]
@abolfazlnasr : it's open source, YOU should take action IF you really want 🤨
