### ISSUE TITLE
Nullable fields in a body to be configurable

### ISSUE THREAD

**Issue by luica13** [tchiotludo/akhq#795]
For viewing message body in AvroToJsonSerializer it was added to show only non_null and non_empty fields. It will be better to have it configurable, as these fields needed to be viewed for many cases(check wether nullable fields are pushed, etc.)

https://github.com/tchiotludo/akhq/compare/0.17.0...0.18.0#diff-e52f62409aed8a22b8fe718f08bb367e172a445c078a145b771dd3c302d0aed8R17

**Comment by tchiotludo** [comment]
Simple here ! 
a PR is welcome to add some configuration properties for that

**Comment by magnusgundersen** [comment]
Did a quick suggestion on solving this feature. https://github.com/tchiotludo/akhq/pull/799
Any thoughs?

**Comment by twobeeb** [comment]
I just encountered this issue recently.

It was very difficult to understand at first because the field defined with AVRO was mandatory yet it was not displayed in AKHQ.
After investigation, the producer set the value "" which doesn't show up in AKHQ in 0.18. 

Message using kafka-avro-console-producer : 
````
{
  "ProductionDay": 1631671200000,
  "Machine": "", <----- Mandatory in AVRO
  "Series": null,  <----- Optional in AVRO
  "Operator": {
    "string": "xxxxx"
  },
  "Product": {
    "SerialNumber": "0014479"
  }
}
````

The same message in AKHQ : 
````
{
  "ProductionDay": 1631671200000,
  "Operator": {
    "string": "xxxxx"
  },
  "Product": {
    "SerialNumber": "0014479"
  }
}
````

I believe the defaults NON_EMPTY and NON_NULL are VERY misleading (NON_EMPTY particularly)
@tchiotludo @magnusgundersen 
What's your opinion on this (the defaults set on PR #799) ?

**Comment by tchiotludo** [comment]
good catch, I remove the `NON_EMPTY` defaults
