### ISSUE TITLE
Zero day vulnerability for older versions of Log4J

### ISSUE THREAD

**Issue by blatyo** [tchiotludo/akhq#944]
https://www.lunasec.io/docs/blog/log4j-zero-day/

~~Temporary workaround seems to be to add `-Dlog4j2.formatMsgNoLookups=true` to the jvm.opts file, since akhq seems to use log4j 1.8.x.~~ That's for 1.10.x

**Comment by blatyo** [comment]
I'm not very familiar with gradle. Is this not pulling in log4j? https://github.com/tchiotludo/akhq/blob/dev/build.gradle#L95

**Comment by blatyo** [comment]
Nevermind, I misinterpreted the name of that dependency.

**Comment by fjuan** [comment]
Hello @tchiotludo 

log4j version 2.13.2 is included as part of the  "kafka-connect-client" version "3.1.1" from sourcelab.

They have released version "4.0.0" with an updated log4j-2.15.0.
Reference: https://github.com/SourceLabOrg/kafka-connect-client/blob/v4.0.0/pom.xml#L64

Even though AKHQ doesn't use the vulnerable log4j, would it make sense to update the kafka-connect-client dependency in order to remove the vulnerability from the released akhq.jar files?

Thanks

**Comment by tchiotludo** [comment]
try to do it here : https://github.com/tchiotludo/akhq/pull/947 
Update all deps :smile:
